version: '3'
services:
  redis:
    image: 'redis:5.0.5'
    container_name: 'redis'
  worker:
    container_name: 'celery_worker'
    build:
      context: .
      dockerfile: containers/Dockerfile.worker
    volumes:
      - .:/app
    depends_on:
      - redis
  flower:
    container_name: 'flower'
    build:
      context: .
      dockerfile: containers/Dockerfile.flower
    ports:
      - 5555:5555
    depends_on:
      - redis
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: containers/Dockerfile.app
    ports:
      - 80:80
    depends_on:
      - redis
      - worker